name: onceuponanai
channels:
  - conda-forge
dependencies:
  - ipykernel=6.15.2
  - python=3.10
  - pandas=1.4.4
  - numpy=1.23.1
  - plotly=5.10.0
  - httpx=0.23.0
  - ciso8601=2.2.0
  - pip
  - pip:
    - jsonpath-ng
    - json-schema-for-humans
  
